### PR TITLE
GPU branch on Julia 1.6

### PR DESCRIPTION
**Pull request by albheim**
Tried out the GPU branch on 1.6, did not work. Merged current master and updated what didn't work. 

Verified that `CuParticles` and ran the tests though I don't think they test any of the GPU capabilities.

Also played around a bit with the speed, comparing it to the normal particles. Not surprisingly the breakpoint for how many particles are needed to make GPU worth it is reduced by the complexity of the function we propagate them through and for a simple function we might need 1e6 particles while for a little more complex one I had the breakpoint at 1e3 particles.

Do what you want with it, fixed it for my own testing but thought I might as well create a PR.

### CODE REVIEW

**Comment by baggepinnen** [comment]
Thanks Albin! I never merged the PR with the GPUParticles since it's a mess to test GPU functionality. It requires a CI infrastructure with GPUs available on the CI machines. I hear that there are some options available in the ecosystem by now, but I'm not sure if the additional complexity it brings to this package is worth it. I have been thinking about refactoring the internals slightly to allow defining new particle types in external packages, if I do that, a package could be created that just provides and tests `CuParticles`.

Your benchmarks are interesting, I never saw a benefit for as low as 1e3 particles last time I tried :)

**Comment by albheim** [comment]
> Your benchmarks are interesting, I never saw a benefit for as low as 1e3 particles last time I tried :)

Yeah, I was a bit surprised since somewhere in the docs I think I found 1e6-1e7 being mentioned as the breakpoint. I ran something like this

```julia
using MonteCarloMeasurements, BenchmarkTools

f1(a, b, c) = a * b^4 + sin(c)
f2(a, b, c) = a * b^4 + sin(c) + exp(b*c) + a^b/c - 4*c*sqrt(a+1)

function test(f, T, N)
    a = T(N, Normal(1f0, 0.1f0))
    b = T(N, Normal(0.3f0, 0.1f0))
    c = T(N, Normal(1f0, 0.1f0))
    @btime $f($a, $b, $c)
end

test(f1, Particles, 1000) # 9.149 μs
test(f1, CuParticles, 1000) # 23.679 μs

test(f2, Particles, 1000) # 94.111 μs
test(f2, CuParticles, 1000) # 74.917 μs
```
which gave that for `f1` and 1000 particles it was a little faster on the cpu, but for `f2` it was a little faster on the gpu. My assumption was just that more calculation means that the overhead of the gpu mattered less, so then we can get a lower breakpoint. But maybe that can't really explain all the difference compared to the numbers you had.

**Comment by baggepinnen** [comment]
I benchmarked on an ODE problem 
https://baggepinnen.github.io/MonteCarloMeasurements.jl/stable/examples/#Differential-Equations-1

It's possible that the functions you tried were so small that the GC didn't trigger on some trials, and since `@btime` reports the minimum timing the GC pressure was not accounted for. I believe the reason that GPU particles have so high overhead is GC pressure, I think the GPU has it's own memory management separate from the Julia standard GC, so they might behave slightly different.

**Comment by albheim** [comment]
Ahh, didn't even know it reported the minimum. Would have thought it was the mean. Here is the last run with `@benchmark` instead
```julia
julia> test(f2, Particles, 1000)
BenchmarkTools.Trial: 
  memory estimate:  52.81 KiB
  allocs estimate:  13
  --------------
  minimum time:     93.786 μs (0.00% GC)
  median time:      96.257 μs (0.00% GC)
  mean time:        100.312 μs (3.36% GC)
  maximum time:     3.598 ms (95.46% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> test(f2, CuParticles, 1000)
BenchmarkTools.Trial: 
  memory estimate:  8.12 KiB
  allocs estimate:  377
  --------------
  minimum time:     92.513 μs (0.00% GC)
  median time:      104.519 μs (0.00% GC)
  mean time:        135.191 μs (3.13% GC)
  maximum time:     175.921 ms (13.20% GC)
  --------------
  samples:          10000
  evals/sample:     1
```

It seems they are handled by the Julia GC at least, but maybe still behave slightly different: https://juliagpu.gitlab.io/CUDA.jl/usage/memory/#Garbage-collection

**Pull request merged**
