### PR TITLE
GPU particles

### PR DESCRIPTION
**Pull request by baggepinnen**
This PR adds a type `CuParticles` that works as regular `Particles` but is backed by a `CuArray`. Expect in the range of 5-7x speedup over `Particles` if the sample size is 1e5 - 1e7. 

Future memory-management improvements to the GPU ecosystem is likely to improve upon this number. 

This PR supersedes #6 as that had gone a bit too stale with time.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
I don't think this ever got docs.

**Comment by baggepinnen** [comment]
No, I ended up reverting the change since the additional dependencies were a hassle. I should probably ensure that the changes are at least available on some branch

**Comment by ChrisRackauckas** [comment]
What about using Requires instead?

**Comment by baggepinnen** [comment]
Requires does unfortunately not solve the problem due to how many methods are defined. 
We define many methods using code generation for each particle type, like [here](https://github.com/baggepinnen/MonteCarloMeasurements.jl/blob/4fba4f0f51ccd2b0063106dcf76017aca80e3005/src/particles.jl#L278). To add `CuParticles` as an optional dependency, this code would unfortunately have to be duplicated. Some of the code generated methods could likely be defined for `AbstractParticles` instead, which would reduce the amount of code generated per particle type.

There's still the problem with the testing though, I'm currently working from a laptop without GPU support, and I don't know how to test the functionality on Travis etc. 

I added some docs hinting at the existence of GPU support here
https://baggepinnen.github.io/MonteCarloMeasurements.jl/latest/performance/

**Comment by baggepinnen** [comment]
The code generation could perhaps be put in a function, similar to how `register_primitive` works. Then new types would only call this function to define all generated methods.

**Pull request merged**
